name: biblebrain_dart
description: A dart wrapper for the Bible Brain (aka Digital Bible Platform v4) API.
version: 2.1.0
repository: https://github.com/MarkIvanDev/biblebrain_dart.git
issue_tracker: https://github.com/MarkIvanDev/biblebrain_dart/issues

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  http: ^1.5.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  build_runner: ^2.9.0
  envied: ^1.3.1
  envied_generator: ^1.3.1
  json_serializable: ^6.11.1
