name: biblebrain_dart
description: A dart wrapper for the Bible Brain (aka Digital Bible Platform v4) API.
version: 1.0.0
repository: https://github.com/MarkIvanDev/biblebrain_dart.git
issue_tracker: https://github.com/MarkIvanDev/biblebrain_dart/issues

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.2
  envied: ^0.2.3
  envied_generator: ^0.2.3
  json_serializable: ^6.5.4
