name: biblebrain_dart
description: A dart wrapper for the Bible Brain (aka Digital Bible Platform v4) API.
version: 1.0.0
repository: https://github.com/MarkIvanDev/biblebrain_dart.git
issue_tracker: https://github.com/MarkIvanDev/biblebrain_dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  build_runner: ^2.4.8
  envied: ^0.5.3
  envied_generator: ^0.5.3
  json_serializable: ^6.5.4
